# coding=utf-8
"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
import ez_setup
ez_setup.use_setuptools()

from setuptools import setup

APP = ['VhostSwitcher.py']
DATA_FILES = ["VhostSwitcher.xib"]
APP_NAME = "VhostSwitcher"
OPTIONS = {
    "iconfile": "img/icon.icns",
    'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "Easily switch Apache VirtualHosts",
        'CFBundleIdentifier': "com.guillaumeca.macos.vhostswitcher",
        'CFBundleVersion': "0.0.1",
        'CFBundleShortVersionString': "0.0.1",
        'NSHumanReadableCopyright': u"Copyright © 2016, Guillaume Carré, All Rights Reserved"
    }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=[
        'py2app'
    ]
)
